### ISSUE TITLE
Update redbean to 2.0

### ISSUE THREAD

**Issue by kissgyorgy** [kissgyorgy/redbean-docker#2]
Redbean 2.0 is out with awesome new features: https://justine.lol/redbean2/

**Comment by shmup** [comment]
Curious how this goes for you. In my current setup, on an M1 mac, I'm running into problems:

```
redbean_1  | standard_init_linux.go:228: exec user process caused: exec format error
eternotes_redbean_1 exited with code 1
```

Stands up fine with redbean 1.4

**Comment by kissgyorgy** [comment]
I updated all `Dockerfile`s, I used the new `--assimilate` feature, see in the release notes: https://justine.lol/redbean2/
Let me know if it works for you!

**Comment by shmup** [comment]
@kissgyorgy It works for me! Weee, great work :)
